language:
  - c

sudo:
  - required

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - cmake
      - realpath

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
