#!/usr/bin/env bash

# Environment
BUILDDIR="$(pwd)"
TMPDIR=$(mktemp -d)
pushd ${TMPDIR}

# Test - install with custom prefix (use sudo to make Travis-CI happy)
sudo "${BUILDDIR}/sget" --prefix /tmp install https://github.com/d99kris/sget
which sget > /dev/null
if [[ ! -f "${HOME}/bin/sget" ]]; then
  echo "not able to install software in custom prefix /tmp/"
  ls -lRa /tmp/  
  exit 1
fi

# Cleanup
popd
rm -rf ${TMPDIR}
exit 0
