#!/usr/bin/env bash

# Environment
BUILDDIR="$(pwd)"
TMPDIR=$(mktemp -d)
pushd ${TMPDIR}

# Test - install with custom prefix
"${BUILDDIR}/sget" --prefix /tmp install https://github.com/d99kris/sget
which sget > /dev/null
if [[ ! -f "/tmp/bin/sget" ]]; then
  echo "not able to install software in custom prefix /tmp"
  exit 1
fi

# Cleanup
popd
rm -rf ${TMPDIR}
exit 0
